using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using Questionable.Model.Common.Converter;
namespace Questionable.Model.Common;

[JsonConverter(typeof(AetheryteConverter))]
public enum EAetheryteLocation
{
    None = 0,

    Gridania = 2,
    GridaniaArcher = 25,
    GridaniaLeatherworker = 26,
    GridaniaLancer = 27,
    GridaniaConjurer = 28,
    GridaniaBotanist = 29,
    GridaniaAmphitheatre = 30,
    GridaniaBlueBadgerGate = 31,
    GridaniaYellowSerpentGate = 32,
    GridaniaWhiteWolfGate = 54,
    GridaniaAirship = 94,

    CentralShroudBentbranchMeadows = 3,
    EastShroudHawthorneHut = 4,
    SouthShroudQuarrymill = 5,
    SouthShroudCampTranquil = 6,
    NorthShroudFallgourdFloat = 7,

    Uldah = 9,
    UldahAdventurers = 33,
    UldahThaumaturge = 34,
    UldahGladiator = 35,
    UldahMiner = 36,
    UldahAlchemist = 37,
    UldahWeaver = 47,
    UldahGoldsmith = 50,
    UldahChamberOfRule = 51,
    UldahAirship = 95,
    UldahGateOfTheSultana = 38,
    UldahGateOfNald = 39,
    UldahGateOfThal = 40,
    UldahSapphireAvenue = 125,

    WesternThanalanHorizon = 17,
    EasternThanalanCampDrybone = 18,
    SouthernThanalanLittleAlaMhigo = 19,
    SouthernThanalanForgottenSprings = 20,
    NorthernThanalanCampBluefog = 21,
    NorthernThanalanCeruleumProcessingPlant = 22,
    CentralThanalanBlackBrushStation = 53,

    Limsa = 8,
    LimsaAftcastle = 41,
    LimsaCulinarian = 42,
    LimsaArcanist = 43,
    LimsaFisher = 44,
    LimsaMarauder = 48,
    LimsaHawkersAlley = 49,
    LimsaZephyrGate = 45,
    LimsaTempestGate = 46,
    LimsaAirship = 93,

    LowerLaNosceaMorabyDrydocks = 10,
    EasternLaNosceaCostaDelSol = 11,
    EasternLaNosceaWineport = 12,
    WesternLaNosceaSwiftperch = 13,
    WesternLaNosceaAleport = 14,
    UpperLaNosceaCampBronzeLake = 15,
    OuterLaNosceaCampOverlook = 16,
    MiddleLaNosceaSummerfordFarms = 52,

    CoerthasCentralHighlandsCampDragonhead = 23,
    MorDhona = 24,
    WolvesDenPier = 55,

    GoldSaucer = 62,
    GoldSaucerEntranceCardSquares = 63,
    GoldSaucerWonderSquareEast = 64,
    GoldSaucerWonderSquareWest = 65,
    GoldSaucerEventSquare = 66,
    GoldSaucerCactpotBoard = 67,
    GoldSaucerRoundSquare = 68,
    GoldSaucerChocoboSquare = 69,
    GoldSaucerMinionSquare = 89,

    Ishgard = 70,
    IshgardForgottenKnight = 80,
    IshgardSkysteelManufactory = 81,
    IshgardBrume = 82,
    IshgardAthenaeumAstrologicum = 83,
    IshgardJeweledCrozier = 84,
    IshgardSaintReymanaudsCathedral = 85,
    IshgardTribunal = 86,
    IshgardLastVigil = 87,
    IshgardGatesOfJudgement = 88,
    IshgardFirmament = 100001,

    FirmamentMendicantsCourt = 2011373,
    FirmamentMattock = 2011374,
    FirmamentNewNest = 2011384,
    FirmanentSaintRoellesDais = 2011385,
    FirmamentFeatherfall = 2011386,
    FirmamentHoarfrostHall = 2011387,
    FirmamentWesternRisensongQuarter = 2011388,
    FirmamentEasternRisensongQuarter = 2011389,

    Idyllshire = 75,
    IdyllshireWest = 90,
    IdyllshirePrologueGate = 91,
    IdyllshireEpilogueGate = 92,

    CoerthasWesternHighlandsFalconsNest = 71,
    SeaOfCloudsCampCloudtop = 72,
    SeaOfCloudsOkZundu = 73,
    AzysLlaHelix = 74,
    DravanianForelandsTailfeather = 76,
    DravanianForelandsAnyxTrine = 77,
    ChurningMistsMoghome = 78,
    ChurningMistsZenith = 79,

    RhalgrsReach = 104,
    RhalgrsReachWest = 121,
    RhalgrsReachNorthEast = 122,
    RhalgrsReachFringesGate = 123,
    RhalgrsReachPeaksGate = 124,

    Kugane = 111,
    KuganeShiokazeHostelry = 112,
    KuganePier1 = 113,
    KuganeThavnairianConsulate = 114,
    KuganeMarkets = 115,
    KuganeBokairoInn = 116,
    KuganeRubyBazaar = 117,
    KuganeSekiseigumiBarracks = 118,
    KuganeRakuzaDistrict = 119,
    KuganeRubyPrice = 120,
    KuganeAirship = 126,

    FringesCastrumOriens = 98,
    FringesPeeringStones = 99,
    PeaksAlaGannha = 100,
    PeaksAlaGhiri = 101,
    LochsPortaPraetoria = 102,
    LochsAlaMhiganQuarter = 103,
    RubySeaTamamizu = 105,
    RubySeaOnokoro = 106,
    YanxiaNamai = 107,
    YanxiaHouseOfTheFierce = 108,
    AzimSteppeReunion = 109,
    AzimSteppeDawnThrone = 110,
    AzimSteppeDhoroIloh = 128,

    DomanEnclave = 127,
    DomanEnclaveNorthern = 129,
    DomanEnclaveSouthern = 130,
    DomanEnclaveOneRiver = 131,
    DomanEnclaveDocks = 162,
    DomanEnclaveGangos = 163,

    Crystarium = 133,
    CrystariumMarkets = 149,
    CrystariumTemenosRookery = 150,
    CrystariumDossalGate = 151,
    CrystariumPendants = 152,
    CrystariumAmaroLaunch = 153,
    CrystariumCrystallineMean = 154,
    CrystariumCabinetOfCuriosity = 155,
    CrystariumTessellation = 156,

    Eulmore = 134,
    EulmoreMainstay = 157,
    EulmoreNightsoilPots = 158,
    EulmoreGloryGate = 159,
    EulmoreSoutheastDerelict = 135,
    EulmorePathToGlory = 160,

    LakelandFortJobb = 132,
    LakelandOstallImperative = 136,
    KholusiaStilltide = 137,
    KholusiaWright = 138,
    KholusiaTomra = 139,
    AmhAraengMordSouq = 140,
    AmhAraengInnAtJourneysHead = 161,
    AmhAraengTwine = 141,
    RaktikaSlitherbough = 142,
    RaktikaFanow = 143,
    IlMhegLydhaLran = 144,
    IlMhegPlaEnni = 145,
    IlMhegWolekdorf = 146,
    TempestOndoCups = 147,
    TempestMacarensesAngle = 148,

    OldSharlayan = 182,
    OldSharlayanStudium = 184,
    OldSharlayanBaldesionAnnex = 185,
    OldSharlayanRostra = 186,
    OldSharlayanLeveilleurEstate = 187,
    OldSharlayanJourneysEnd = 188,
    OldSharlayanScholarsHarbor = 189,
    OldSharlayanHallOfArtifice = 190,

    RadzAtHan = 183,
    RadzAtHanMeghaduta = 191,
    RadzAtHanRuveydahFibers = 192,
    RadzAtHanAirship = 193,
    RadzAtHanAlzadaalsPeace = 194,
    RadzAtHanHallOfTheRadiantHost = 195,
    RadzAtHanMehrydesMeyhane = 196,
    RadzAtHanKama = 198,
    RadzAtHanHighCrucible = 199,
    RadzAtHanGateOfFirstSight = 197,

    LabyrinthosArcheion = 166,
    LabyrinthosSharlayanHamlet = 167,
    LabyrinthosAporia = 168,
    ThavnairYedlihmad = 169,
    ThavnairGreatWork = 170,
    ThavnairPalakasStand = 171,
    GarlemaldCampBrokenGlass = 172,
    GarlemaldTertium = 173,
    MareLamentorumSinusLacrimarum = 174,
    MareLamentorumBestwaysBurrow = 175,
    ElpisAnagnorisis = 176,
    ElpisTwelveWonders = 177,
    ElpisPoietenOikos = 178,
    UltimaThuleReahTahra = 179,
    UltimaThuleAbodeOfTheEa = 180,
    UltimaThuleBaseOmicron = 181,

    Tuliyollal = 216,

    TuliyollalDirigibleLanding = 218,
    TuliyollalTheResplendentQuarter = 219,
    TuliyollalTheForardCabins = 220,
    TuliyollalBaysideBevyMarketplace = 221,
    TuliyollalVollokShoonsa = 222,
    TuliyollalWachumeqimeqi = 223,
    TuliyollalBrightploomPost = 224,
    TuliyollalArchOfTheDawnUrqopacha = 225,
    TuliyollalArchOfTheDawnKozamauka = 226,
    TuliyollalIhuykatumu = 227,
    TuliyollalDirigibleLandingYakTel = 228,
    TuliyollalXakTuralSkygate = 229,
    TuliyollalPhantomVillage = 239,

    SolutionNine = 217,
    SolutionNineInformationCenter = 230,
    SolutionNineTrueVue = 231,
    SolutionNineNeonStein = 232,
    SolutionNineTheArcadion = 233,
    SolutionNineResolution = 234,
    SolutionNineNexusArcade = 235,
    SolutionNineResidentialSector = 236,
    SolutionNineScanningPortNine = 237,

    UrqopachaWachunpelo = 200,
    UrqopachaWorlarsEcho = 201,
    KozamaukaOkHanu = 202,
    KozamaukaManyFires = 203,
    KozamaukaEarthenshire = 204,
    KozamaukaDockPoga = 238,
    YakTelIqBraax = 205,
    YakTelMamook = 206,
    ShaaloaniHhusatahwi = 207,
    ShaaloaniShesheneweziSprings = 208,
    ShaaloaniMehwahhetsoan = 209,
    HeritageFoundYyasulaniStation = 210,
    HeritageFoundTheOutskirts = 211,
    HeritageFoundElectropeStrike = 212,
    LivingMemoryLeynodeMnemo = 213,
    LivingMemoryLeynodePyro = 214,
    LivingMemoryLeynodeAero = 215
}

public static class EAetheryteLocationExtensions
{
    private readonly static IReadOnlyList<EAetheryteLocation> aethernetShards = [
        EAetheryteLocation.GridaniaArcher,
        EAetheryteLocation.GridaniaLeatherworker,
        EAetheryteLocation.GridaniaLancer,
        EAetheryteLocation.GridaniaConjurer,
        EAetheryteLocation.GridaniaBotanist,
        EAetheryteLocation.GridaniaAmphitheatre,
        EAetheryteLocation.GridaniaBlueBadgerGate,
        EAetheryteLocation.GridaniaYellowSerpentGate,
        EAetheryteLocation.GridaniaWhiteWolfGate,
        EAetheryteLocation.GridaniaAirship,

        EAetheryteLocation.UldahAdventurers,
        EAetheryteLocation.UldahThaumaturge,
        EAetheryteLocation.UldahGladiator,
        EAetheryteLocation.UldahMiner,
        EAetheryteLocation.UldahAlchemist,
        EAetheryteLocation.UldahWeaver,
        EAetheryteLocation.UldahGoldsmith,
        EAetheryteLocation.UldahChamberOfRule,
        EAetheryteLocation.UldahAirship,
        EAetheryteLocation.UldahGateOfTheSultana,
        EAetheryteLocation.UldahGateOfNald,
        EAetheryteLocation.UldahGateOfThal,
        EAetheryteLocation.UldahSapphireAvenue,

        EAetheryteLocation.LimsaAftcastle,
        EAetheryteLocation.LimsaCulinarian,
        EAetheryteLocation.LimsaArcanist,
        EAetheryteLocation.LimsaFisher,
        EAetheryteLocation.LimsaMarauder,
        EAetheryteLocation.LimsaHawkersAlley,
        EAetheryteLocation.LimsaZephyrGate,
        EAetheryteLocation.LimsaTempestGate,
        EAetheryteLocation.LimsaAirship,

        EAetheryteLocation.GoldSaucerEntranceCardSquares,
        EAetheryteLocation.GoldSaucerWonderSquareEast,
        EAetheryteLocation.GoldSaucerWonderSquareWest,
        EAetheryteLocation.GoldSaucerEventSquare,
        EAetheryteLocation.GoldSaucerCactpotBoard,
        EAetheryteLocation.GoldSaucerRoundSquare,
        EAetheryteLocation.GoldSaucerChocoboSquare,
        EAetheryteLocation.GoldSaucerMinionSquare,

        EAetheryteLocation.IshgardForgottenKnight,
        EAetheryteLocation.IshgardSkysteelManufactory,
        EAetheryteLocation.IshgardBrume,
        EAetheryteLocation.IshgardAthenaeumAstrologicum,
        EAetheryteLocation.IshgardJeweledCrozier,
        EAetheryteLocation.IshgardSaintReymanaudsCathedral,
        EAetheryteLocation.IshgardTribunal,
        EAetheryteLocation.IshgardLastVigil,
        EAetheryteLocation.IshgardGatesOfJudgement,
        EAetheryteLocation.IshgardFirmament,

        EAetheryteLocation.FirmamentMendicantsCourt,
        EAetheryteLocation.FirmamentMattock,
        EAetheryteLocation.FirmamentNewNest,
        EAetheryteLocation.FirmanentSaintRoellesDais,
        EAetheryteLocation.FirmamentFeatherfall,
        EAetheryteLocation.FirmamentHoarfrostHall,
        EAetheryteLocation.FirmamentWesternRisensongQuarter,
        EAetheryteLocation.FirmamentEasternRisensongQuarter,

        EAetheryteLocation.IdyllshireWest,
        EAetheryteLocation.IdyllshirePrologueGate,
        EAetheryteLocation.IdyllshireEpilogueGate,

        EAetheryteLocation.RhalgrsReachWest,
        EAetheryteLocation.RhalgrsReachNorthEast,
        EAetheryteLocation.RhalgrsReachFringesGate,
        EAetheryteLocation.RhalgrsReachPeaksGate,

        EAetheryteLocation.KuganeShiokazeHostelry,
        EAetheryteLocation.KuganePier1,
        EAetheryteLocation.KuganeThavnairianConsulate,
        EAetheryteLocation.KuganeMarkets,
        EAetheryteLocation.KuganeBokairoInn,
        EAetheryteLocation.KuganeRubyBazaar,
        EAetheryteLocation.KuganeSekiseigumiBarracks,
        EAetheryteLocation.KuganeRakuzaDistrict,
        EAetheryteLocation.KuganeRubyPrice,
        EAetheryteLocation.KuganeAirship,

        EAetheryteLocation.DomanEnclaveNorthern,
        EAetheryteLocation.DomanEnclaveSouthern,
        EAetheryteLocation.DomanEnclaveOneRiver,
        EAetheryteLocation.DomanEnclaveDocks,
        EAetheryteLocation.DomanEnclaveGangos,

        EAetheryteLocation.CrystariumMarkets,
        EAetheryteLocation.CrystariumTemenosRookery,
        EAetheryteLocation.CrystariumDossalGate,
        EAetheryteLocation.CrystariumPendants,
        EAetheryteLocation.CrystariumAmaroLaunch,
        EAetheryteLocation.CrystariumCrystallineMean,
        EAetheryteLocation.CrystariumCabinetOfCuriosity,
        EAetheryteLocation.CrystariumTessellation,

        EAetheryteLocation.EulmoreMainstay,
        EAetheryteLocation.EulmoreNightsoilPots,
        EAetheryteLocation.EulmoreGloryGate,
        EAetheryteLocation.EulmoreSoutheastDerelict,
        EAetheryteLocation.EulmorePathToGlory,

        EAetheryteLocation.OldSharlayanStudium,
        EAetheryteLocation.OldSharlayanBaldesionAnnex,
        EAetheryteLocation.OldSharlayanRostra,
        EAetheryteLocation.OldSharlayanLeveilleurEstate,
        EAetheryteLocation.OldSharlayanJourneysEnd,
        EAetheryteLocation.OldSharlayanScholarsHarbor,
        EAetheryteLocation.OldSharlayanHallOfArtifice,

        EAetheryteLocation.RadzAtHanMeghaduta,
        EAetheryteLocation.RadzAtHanRuveydahFibers,
        EAetheryteLocation.RadzAtHanAirship,
        EAetheryteLocation.RadzAtHanAlzadaalsPeace,
        EAetheryteLocation.RadzAtHanHallOfTheRadiantHost,
        EAetheryteLocation.RadzAtHanMehrydesMeyhane,
        EAetheryteLocation.RadzAtHanKama,
        EAetheryteLocation.RadzAtHanHighCrucible,
        EAetheryteLocation.RadzAtHanGateOfFirstSight,

        EAetheryteLocation.TuliyollalDirigibleLanding,
        EAetheryteLocation.TuliyollalTheResplendentQuarter,
        EAetheryteLocation.TuliyollalTheForardCabins,
        EAetheryteLocation.TuliyollalBaysideBevyMarketplace,
        EAetheryteLocation.TuliyollalVollokShoonsa,
        EAetheryteLocation.TuliyollalWachumeqimeqi,
        EAetheryteLocation.TuliyollalBrightploomPost,
        EAetheryteLocation.TuliyollalArchOfTheDawnUrqopacha,
        EAetheryteLocation.TuliyollalArchOfTheDawnKozamauka,
        EAetheryteLocation.TuliyollalIhuykatumu,
        EAetheryteLocation.TuliyollalDirigibleLandingYakTel,
        EAetheryteLocation.TuliyollalXakTuralSkygate,
        EAetheryteLocation.TuliyollalPhantomVillage,

        EAetheryteLocation.SolutionNineInformationCenter,
        EAetheryteLocation.SolutionNineTrueVue,
        EAetheryteLocation.SolutionNineNeonStein,
        EAetheryteLocation.SolutionNineTheArcadion,
        EAetheryteLocation.SolutionNineResolution,
        EAetheryteLocation.SolutionNineNexusArcade,
        EAetheryteLocation.SolutionNineResidentialSector,
        EAetheryteLocation.SolutionNineScanningPortNine,
    ];
    public static bool IsAethernetShard(this EAetheryteLocation aetheryteLocation) =>
        aethernetShards.Contains(aetheryteLocation);
    public static bool IsFirmamentAetheryte(this EAetheryteLocation aetheryteLocation) =>
        aetheryteLocation is EAetheryteLocation.IshgardFirmament
            or EAetheryteLocation.FirmamentMendicantsCourt
            or EAetheryteLocation.FirmamentMattock
            or EAetheryteLocation.FirmamentNewNest
            or EAetheryteLocation.FirmanentSaintRoellesDais
            or EAetheryteLocation.FirmamentFeatherfall
            or EAetheryteLocation.FirmamentHoarfrostHall
            or EAetheryteLocation.FirmamentWesternRisensongQuarter
            or EAetheryteLocation.FirmamentEasternRisensongQuarter;

    public static string ToFriendlyString(this EAetheryteLocation aetheryteLocation) =>
        aetheryteLocation switch
        {
            EAetheryteLocation.None => "无",
            EAetheryteLocation.Gridania => "格里达尼亚新街",
            EAetheryteLocation.GridaniaArcher => "弓箭手行会前",
            EAetheryteLocation.GridaniaLeatherworker => "市场（制革匠行会前）",
            EAetheryteLocation.GridaniaLancer => "枪术师行会前",
            EAetheryteLocation.GridaniaConjurer => "幻术师行会前",
            EAetheryteLocation.GridaniaBotanist => "园艺工行会前",
            EAetheryteLocation.GridaniaAmphitheatre => "米·凯特露天剧场",
            EAetheryteLocation.GridaniaBlueBadgerGate => "青貉门（中央林区东侧方面）",
            EAetheryteLocation.GridaniaYellowSerpentGate => "黄蛇门（北部林区方面）",
            EAetheryteLocation.GridaniaWhiteWolfGate => "白狼门（中央林区西侧方面）",
            EAetheryteLocation.GridaniaAirship => "格里达尼亚飞艇坪",

            EAetheryteLocation.Uldah => "乌尔达哈现世回廊",
            EAetheryteLocation.UldahAdventurers => "冒险者行会前",
            EAetheryteLocation.UldahThaumaturge => "咒术师行会前",
            EAetheryteLocation.UldahGladiator => "剑术师行会前（斗技场）",
            EAetheryteLocation.UldahMiner => "采矿工行会前（天青斗场）",
            EAetheryteLocation.UldahAlchemist => "炼金术士行会前",
            EAetheryteLocation.UldahWeaver => "裁衣匠行会前",
            EAetheryteLocation.UldahGoldsmith => "雕金匠行会前",
            EAetheryteLocation.UldahChamberOfRule => "乌尔达哈王政厅",
            EAetheryteLocation.UldahAirship => "乌尔达哈飞艇坪",
            EAetheryteLocation.UldahGateOfTheSultana => "娜娜莫新门（西萨纳兰方面）",
            EAetheryteLocation.UldahGateOfNald => "纳尔之门（中萨纳兰北方面）",
            EAetheryteLocation.UldahGateOfThal => "札尔之门（中萨纳兰南方面）",
            EAetheryteLocation.UldahSapphireAvenue => "市场（蓝玉大街国际市场）",

            EAetheryteLocation.Limsa => "利姆萨·罗敏萨下层甲板",
            EAetheryteLocation.LimsaAftcastle => "冒险者行会前（锻铁匠行会/铸甲匠行会/黑涡团）",
            EAetheryteLocation.LimsaCulinarian => "烹调师行会前（俾斯麦餐厅）",
            EAetheryteLocation.LimsaArcanist => "秘术师行会前（渡轮码头）",
            EAetheryteLocation.LimsaFisher => "捕鱼人行会前（双剑师行会）",
            EAetheryteLocation.LimsaMarauder => "斧术师行会前（珊瑚塔）",
            EAetheryteLocation.LimsaHawkersAlley => "市场（国际广场）",
            EAetheryteLocation.LimsaZephyrGate => "和风陆门（中拉诺西亚方面）",
            EAetheryteLocation.LimsaTempestGate => "暴风陆门（拉诺西亚低地方面）",
            EAetheryteLocation.LimsaAirship => "利姆萨·罗敏萨飞艇坪",

            EAetheryteLocation.GoldSaucer => "金碟游乐场",
            EAetheryteLocation.GoldSaucerEntranceCardSquares => "入口广场（幻卡广场）",
            EAetheryteLocation.GoldSaucerWonderSquareEast => "奇妙广场东区（多玛方城战）",
            EAetheryteLocation.GoldSaucerWonderSquareWest => "奇妙广场西区",
            EAetheryteLocation.GoldSaucerEventSquare => "演出广场",
            EAetheryteLocation.GoldSaucerCactpotBoard => "仙人彩",
            EAetheryteLocation.GoldSaucerRoundSquare => "圆形广场",
            EAetheryteLocation.GoldSaucerChocoboSquare => "陆行鸟广场",
            EAetheryteLocation.GoldSaucerMinionSquare => "陆行鸟广场（宠物广场）",

            EAetheryteLocation.Ishgard => "伊修加德基础层",
            EAetheryteLocation.IshgardForgottenKnight => "忘忧骑士亭前（圣瓦勒鲁瓦扬广场）",
            EAetheryteLocation.IshgardSkysteelManufactory => "天钢机工房前（圣蕾内特广场）",
            EAetheryteLocation.IshgardBrume => "云雾街",
            EAetheryteLocation.IshgardAthenaeumAstrologicum => "圣冈里奥尔占星院前（伊修加德飞艇坪）",
            EAetheryteLocation.IshgardJeweledCrozier => "市场（宝杖大街）",
            EAetheryteLocation.IshgardSaintReymanaudsCathedral => "圣雷马诺大圣堂（圣恩达利姆神学院）",
            EAetheryteLocation.IshgardTribunal => "神圣裁判所",
            EAetheryteLocation.IshgardLastVigil => "终卫要塞（福尔唐伯爵府）",
            EAetheryteLocation.IshgardGatesOfJudgement => "圣徒门（库尔札斯中央高地方面）",

            EAetheryteLocation.Idyllshire => "田园郡",
            EAetheryteLocation.IdyllshireWest => "田园郡西",
            EAetheryteLocation.IdyllshirePrologueGate => "序言门（龙堡内陆低地西方面）",
            EAetheryteLocation.IdyllshireEpilogueGate => "后记门（龙堡内陆低地东方面）",
            EAetheryteLocation.RhalgrsReach => "神拳痕",
            EAetheryteLocation.RhalgrsReachWest => "神拳痕西",
            EAetheryteLocation.RhalgrsReachNorthEast => "神拳痕东北",
            EAetheryteLocation.RhalgrsReachFringesGate => "基拉巴尼亚边区方面",
            EAetheryteLocation.RhalgrsReachPeaksGate => "基拉巴尼亚山区方面",
            EAetheryteLocation.Kugane => "黄金港",
            EAetheryteLocation.KuganeShiokazeHostelry => "潮风亭前",
            EAetheryteLocation.KuganePier1 => "第一防波堤",
            EAetheryteLocation.KuganeThavnairianConsulate => "拉札罕大使馆前",
            EAetheryteLocation.KuganeMarkets => "市场（小金街）",
            EAetheryteLocation.KuganeBokairoInn => "望海楼",
            EAetheryteLocation.KuganeRubyBazaar => "乌尔达哈商会馆前",
            EAetheryteLocation.KuganeSekiseigumiBarracks => "赤诚组营房南",
            EAetheryteLocation.KuganeRakuzaDistrict => "乐座街",
            EAetheryteLocation.KuganeRubyPrice => "红玉海方面",
            EAetheryteLocation.KuganeAirship => "黄金港飞艇坪",

            EAetheryteLocation.DomanEnclave => "多玛飞地",
            EAetheryteLocation.DomanEnclaveNorthern => "多玛飞地北（无二庭园/农耕地）",
            EAetheryteLocation.DomanEnclaveSouthern => "多玛飞地南（栗斋学堂）",
            EAetheryteLocation.DomanEnclaveOneRiver => "无二江流域（延夏方面）",
            EAetheryteLocation.DomanEnclaveDocks => "码头",
            EAetheryteLocation.DomanEnclaveGangos => "甘戈斯",

            EAetheryteLocation.Crystarium => "水晶都",
            EAetheryteLocation.CrystariumMarkets => "宇宙和音市场",
            EAetheryteLocation.CrystariumTemenosRookery => "圣林牧场",
            EAetheryteLocation.CrystariumDossalGate => "幔布门前（观星室）",
            EAetheryteLocation.CrystariumPendants => "悬挂公馆前",
            EAetheryteLocation.CrystariumAmaroLaunch => "阿马罗栈桥前",
            EAetheryteLocation.CrystariumCrystallineMean => "中庸工艺馆前",
            EAetheryteLocation.CrystariumCabinetOfCuriosity => "博物陈列馆前",
            EAetheryteLocation.CrystariumTessellation => "密铺铁桥（雷克兰德方面）",
            EAetheryteLocation.Eulmore => "游末邦",
            EAetheryteLocation.EulmoreMainstay => "承重柱",
            EAetheryteLocation.EulmoreNightsoilPots => "腐臭花园",
            EAetheryteLocation.EulmoreGloryGate => "光荣门",
            EAetheryteLocation.EulmoreSoutheastDerelict => "废船街东南",
            EAetheryteLocation.EulmorePathToGlory => "光荣路（珂露西亚岛方面）",

            EAetheryteLocation.OldSharlayan => "旧萨雷安",
            EAetheryteLocation.OldSharlayanStudium => "萨雷安魔法大学",
            EAetheryteLocation.OldSharlayanBaldesionAnnex => "巴尔德西昂分馆前",
            EAetheryteLocation.OldSharlayanRostra => "哲学家广场",
            EAetheryteLocation.OldSharlayanLeveilleurEstate => "莱韦耶勒尔府前",
            EAetheryteLocation.OldSharlayanJourneysEnd => "漂流的终点",
            EAetheryteLocation.OldSharlayanScholarsHarbor => "知识神海港",
            EAetheryteLocation.OldSharlayanHallOfArtifice => "诡巧大厅（迷津方面）",
            EAetheryteLocation.RadzAtHan => "拉札罕",
            EAetheryteLocation.RadzAtHanMeghaduta => "云使宫前",
            EAetheryteLocation.RadzAtHanRuveydahFibers => "鲁维达纺丝局前",
            EAetheryteLocation.RadzAtHanAirship => "拉札罕飞艇坪",
            EAetheryteLocation.RadzAtHanAlzadaalsPeace => "阿尔扎达尔庙前",
            EAetheryteLocation.RadzAtHanHallOfTheRadiantHost => "星战士团大本营前",
            EAetheryteLocation.RadzAtHanMehrydesMeyhane => "梅丽德酒房",
            EAetheryteLocation.RadzAtHanKama => "卡玛爱区",
            EAetheryteLocation.RadzAtHanHighCrucible => "炼金术制药堂",
            EAetheryteLocation.RadzAtHanGateOfFirstSight => "真眼门（萨维奈岛方面）",

            EAetheryteLocation.Tuliyollal => "图莱尤拉",
            EAetheryteLocation.TuliyollalDirigibleLanding => "气球起降所前",
            EAetheryteLocation.TuliyollalTheResplendentQuarter => "翼镜街",
            EAetheryteLocation.TuliyollalTheForardCabins => "船头小屋前",
            EAetheryteLocation.TuliyollalBaysideBevyMarketplace => "海岸鸟群市场",
            EAetheryteLocation.TuliyollalVollokShoonsa => "沃洛克联王宫前",
            EAetheryteLocation.TuliyollalWachumeqimeqi => "珠串万货街",
            EAetheryteLocation.TuliyollalBrightploomPost => "鲜羽兵站前",
            EAetheryteLocation.TuliyollalArchOfTheDawnUrqopacha => "古鲁加加凯旋门（奥阔帕恰山方面）",
            EAetheryteLocation.TuliyollalArchOfTheDawnKozamauka => "古鲁加加凯旋门（克扎玛乌卡湿地方面）",
            EAetheryteLocation.TuliyollalIhuykatumu => "生息河岸（克扎玛乌卡湿地方面）",
            EAetheryteLocation.TuliyollalDirigibleLandingYakTel => "气球起降所（亚克特尔树海方面）",
            EAetheryteLocation.TuliyollalXakTuralSkygate => "萨卡图拉尔关门（夏劳尼荒野方面）",
            EAetheryteLocation.TuliyollalPhantomVillage => "幻影村",
            EAetheryteLocation.SolutionNine => "九号解决方案",
            EAetheryteLocation.SolutionNineInformationCenter => "信息中心前",
            EAetheryteLocation.SolutionNineTrueVue => "真唯大道",
            EAetheryteLocation.SolutionNineNeonStein => "霓虹酒杯前",
            EAetheryteLocation.SolutionNineTheArcadion => "阿卡狄亚协会前",
            EAetheryteLocation.SolutionNineResolution => "解答所",
            EAetheryteLocation.SolutionNineNexusArcade => "联合商城",
            EAetheryteLocation.SolutionNineResidentialSector => "居住区域",
            EAetheryteLocation.SolutionNineScanningPortNine => "九层检查口（遗产之地方面）",

            EAetheryteLocation.IshgardFirmament => "天穹街",
            EAetheryteLocation.FirmamentMendicantsCourt => "无名众人广场",
            EAetheryteLocation.FirmamentMattock => "十字镐大街",
            EAetheryteLocation.FirmamentNewNest => "新巢居住区",
            EAetheryteLocation.FirmanentSaintRoellesDais => "圣罗埃勒广场",
            EAetheryteLocation.FirmamentFeatherfall => "落羽商业区",
            EAetheryteLocation.FirmamentHoarfrostHall => "白霜官舍",
            EAetheryteLocation.FirmamentWesternRisensongQuarter => "西升歌文化区",
            EAetheryteLocation.FirmamentEasternRisensongQuarter => "东升歌文化区",

            _ => aetheryteLocation.ToString(),
        };
}
